{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.istio.gateway.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{ toYaml .Values.istio.gateway.selector | indent 2 }}
  servers:
  - port:
      number: {{ .Values.istio.gateway.port.number }}
      name: {{ .Values.istio.gateway.port.name }}
      protocol: {{ .Values.istio.gateway.port.protocol }}
    hosts:
    {{ toYaml .Values.istio.gateway.hosts | indent 4 }}
{{- end }}
