replicaCount: 1
image:
  repository: ghcr.io/juliosw/ecomarket-api1
  tag: 46b3fedbbdffecdabeed87e3e6c485170fb96c93
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
rollout:
  canary:
    steps:
      - setWeight: 10
      - pause: { duration: 5m }
      - setWeight: 50
      - pause: { duration: 5m }
      - setWeight: 100
istio:
  virtualService:
    hosts:
      - "api1.tunnelsw.com"
    gateways:
      - "istio-ingressgateway"
  destinationRule:
    subsets:
      - name: v1
        labels:
          version: v1
      - name: v2
        labels:
          version: v2
configmap:  # Adicionado
  data:
    ENVIRONMENT: "production"
    LOG_LEVEL: "INFO"
    apiToken: "api1token"
