replicaCount: 1
image:
  repository: ghcr.io/juliosw/ecomarket-api1
  tag: 0090352c9b5b434af7bf7d45f7a59b2d5e021017
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
hpa:
  enabled: false  # Desativado para garantir 1 pod fixo
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
istio:
  virtualService:
    hosts:
      - "api1.tunnelsw.com"
    gateways:
      - "istio-ingressgateway"
  destinationRule:
    subsets:
      - name: v1
        labels:
          version: v1
      - name: v2
        labels:
          version: v2
configmap:
  data:
    ENVIRONMENT: "production"
    LOG_LEVEL: "INFO"
    apiToken: "api1token"
