apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ecomarket
spec:
  generators:
  - git:
      repoURL: https://github.com/juliosw/ecomarket.git
      revision: main
      directories:
      - path: charts/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/juliosw/ecomarket.git
        targetRevision: main
        path: '{{path}}'
        helm:
          valueFiles:
          - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
