replicaCount: 3
image:
  repository: ghcr.io/juliosw/ecomarket-frontend
  tag: 0090352c9b5b434af7bf7d45f7a59b2d5e021017
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
hpa:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
rollout:
  canary:
    steps:
      - setWeight: 10
      - pause: { duration: 5m }
      - setWeight: 50
      - pause: { duration: 5m }
      - setWeight: 100
istio:
  virtualService:
    hosts:
      - "app.tunnelsw.com"
    gateways:
      - "istio-ingressgateway"
  destinationRule:
    subsets:
      - name: v1
        labels:
          version: v1
      - name: v2
        labels:
          version: v2
configmap:
  data:
    ENVIRONMENT: "production"
    LOG_LEVEL: "INFO"
    apiToken: "frontendtoken"
