apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ "ecomarket_user" | b64enc }}
  password: {{ "ecomarket_pass" | b64enc }}
