apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecomarket
spec:
  project: default
  source:
    repoURL: 'https://github.com/juliosw/ecomarket.git'
    path: k8s/base
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true