apiVersion: v2
name: gateway
description: A Helm chart for Ecomarket Istio Ingress Gateway configuration
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: istio
    version: "1.x.x"
    condition: istio.enabled
