istio:
  enabled: false
  gateway:
    name: "istio-ingressgateway"
    hosts:
      - "app.tunnelsw.com"
      - "api1.tunnelsw.com"
      - "api2.tunnelsw.com"
    port:
      number: 80
      name: http
      protocol: HTTP
    selector:
      istio: ingressgateway  # Conecta ao istio-ingressgateway existente
