apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  ENVIRONMENT: {{ .Values.configmap.data.ENVIRONMENT | quote }}
  LOG_LEVEL: {{ .Values.configmap.data.LOG_LEVEL | quote }}
  apiToken: {{ .Values.configmap.data.apiToken | quote }}
