apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-virtualservice
  labels:
    app: {{ .Release.Name }}
spec:
  hosts:
  {{- range .Values.istio.virtualService.hosts }}
    - {{ . }}
  {{- end }}
  gateways:
  {{- range .Values.istio.virtualService.gateways }}
    - {{ . }}
  {{- end }}
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}-service
        subset: v1
      weight: 100
    - destination:
        host: {{ .Release.Name }}-service
        subset: v2
      weight: 0
