apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: api2
spec:
  replicas: 3
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 300s}
      - setWeight: 60
      - pause: {duration: 300s}
      - setWeight: 100
  selector:
    matchLabels:
      app: api2
  template:
    metadata:
      labels:
        app: api2
    spec:
      containers:
      - name: api2
        image: ghcr.io/juliosw/ecomarket-api2:{{ .Values.version }}
        ports:
        - containerPort: 8000
