apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-canary-service
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
  selector:
    app: {{ .Release.Name }}
