{{- if .Values.istio.destinationRule }}
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ .Release.Name }}-dr
  namespace: {{ .Release.Namespace }}
spec:
  host: {{ .Release.Name }}-service
  subsets:
  - name: v1
    labels:
      version: v1
{{- end }}
