{{- if .Values.istio.virtualService }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-vs
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  {{- range .Values.istio.virtualService.hosts }}
  - {{ . | quote }}
  {{- end }}
  gateways:
  {{- range .Values.istio.virtualService.gateways }}
  - {{ . | quote }}
  {{- end }}
  http:
  - route:
    - destination:
        host: {{ .Release.Name }}-service
        subset: v1
{{- end }}
